---
- name: Join Control Plane
  block:
    - name: Join Control Plane
      command: "{{ hostvars[groups['master'][0]]['join_command'] }}"
    - name: Wait for kubelet to be ready
      wait_for:
        port: 6443
        delay: 10
        timeout: 300
  when: groups['master'][0] != inventory_hostname