---
- name: Install HAProxy and keepalived
  apt:
    name: ["haproxy", "keepalived"]
    update_cache: yes
- name: Generate a new password for Keepalived
  set_fact:
    passwd: "{{ lookup('password', '/dev/null', length=16) }}"
- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
- name: Ensure HAProxy is running
  service:
    name: haproxy
    state: restarted
    enabled: yes
- name: Ensure Keepalived is running
  service:
    name: keepalived
    state: restarted
    enabled: yes