---
- name: Create bootstrap token
  shell: "echo $(openssl rand -hex 3).$(openssl rand -hex 8)"
  register: bootstrap_token
- name: Copy kubeadm init config
  template:
    src: templates/init_kubelet.yaml.j2
    dest: /tmp/init_kubelet.yaml
- name: Initialize kubeadm
  command: kubeadm init --config=/tmp/init_kubelet.yaml --upload-certs
  when: groups['master'][0] == inventory_hostname
- name: Get kube admin config
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: outputs
  when: groups['master'][0] == inventory_hostname
- name: Create kubeadm join command
  command: kubeadm token create --print-join-command --ttl=0
  when: groups['master'][0] == inventory_hostname
  register: kubeadm_join_command
- name: Set fact for kubeadm join command
  set_fact:
    join_command: "{{ kubeadm_join_command.stdout }}"
  when: groups['master'][0] == inventory_hostname
- name: Join Control Plane
  command: "{{ hostvars[groups['master'][0]]['join_command'] }} --control-plane"
  when: groups['master'][0] != inventory_hostname